version: "3.9"
   
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    build: .
    command: python3 main.py
    restart: always
    environment:
      - DSN=postgresql+asyncpg://postgres:qwerty@db:5432/postgres
    ports:
      - "80:8080"
    depends_on:
      - db